// Generated by CoffeeScript 1.4.0
(function() {
  var isAppropriateSystemImportCall, t;

  t = require('babel-types');

  module.exports = function() {
    return {
      visitor: {
        CallExpression: function(path, state) {
          var bundleID, bundles, bundlesLayout;
          if (!isAppropriateSystemImportCall(path.node)) {
            return;
          }
          bundlesLayout = state.opts.bundlesLayout;
          bundleID = bundlesLayout.getBundleIDForModule(path.node["arguments"][0].value);
          bundles = bundleID.split('.');
          bundles.splice(0, 1);
          bundles = bundles.map(function(id) {
            return t.stringLiteral('bundle.' + id);
          });
          return path.replaceWith(t.callExpression(t.identifier('loadBundles'), [t.arrayExpression(bundles)]));
        }
      }
    };
  };

  isAppropriateSystemImportCall = function(node) {
    return node.callee.type === 'MemberExpression' && node.callee.object.name === 'System' && node.callee.property.name === 'import' && node["arguments"].length === 1 && node["arguments"][0].type === 'StringLiteral';
  };

}).call(this);
